package com.app.budget.constate;

public enum SousMenuType {
    ECONOMIQUE,
    PROGRAMMATIQUE,
    SOUR_FINANCEMENT,
    PREVISION_PAR_PROJET_ET_RAPPORTS,
    PREVISION_PAR_CATEGORIE_ET_RAPPORTS,
    PREVISION_PAR_ACTIVITE_ET_RAPPORTS,
    ENGAGEMENT,
    LIQUIDATION,
    TRAITEMENT_ENGAGEMENT,
    TRAITEMENT_LIQUIDATION,
    RAPPORT_ENGANGEMENT,
    RAPPORT_LIQUIDATION,
    RAPPORT_EXECITON
}
